/**
 * Example Service API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */



/**
 * A validation error
 */
export interface ErrorItem { 
    /**
     * Default Message. Any further information.
     */
    ["message"]?: string;
    /**
     * {capability-name}.api.{api-key-name}. For generated validation errors this is the path in the document the error resolves to. e.g. object name + \'.\' + field
     */
    ["key"]?: string;
    /**
     * Context can be anything used to construct localised messages.
     */
    ["context"]?: object;
}

