/**
 * Example Service API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */



export interface ExchangeRateItem { 
    /**
     * Exchange rate value.
     */
    ["rate"]: number;
    /**
     * Source(send) currency code
     */
    ["source"]: string;
    /**
     * Target(receive) currency code
     */
    ["target"]: string;
    /**
     * Timestamp for exchange rate.
     */
    ["time"]: string;
}

