/**
 * Example Service API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */



/**
 * Represents HTTP 500 Internal Server Error
 */
export interface InternalServerError { 
    /**
     * Further Information
     */
    ["message"]: string;
}

