/**
 * Example Service API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */



export interface NotAcceptableError { 
    ["message"]?: string;
    /**
     * List of supported media types for this endpoint
     */
    ["supportedMediaTypes"]?: Array<string>;
}

